services:
  app:
    build: 
      context : .
      dockerfile : ${DOCKERFILE:-Dockerfile.dev}
    ports:
      - "8000:8080"
    volumes:
      - ./src:/app/src   
      - ./target:/app/target  
      - ~/.m2:/root/.m2       
    env_file:
      - .env
    environment:
      - SPRING_DATA_MONGODB_HOST = mongodb
      - SPRING_DATA_MONGODB_PORT = 27017
      - SPRING_DATA_MONGODB_DATABASE = InchiriazaUsor
      - GOOGLE_CLIENT_ID 
      - GOOGLE_CLIENT_SECRET 
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - app-network


  mongodb:
    image: mongo:latest
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    ports:
      - "27016:27017"
    volumes:
      - mongodb_data:/data/db
    # serviciul mongodb face parte din reteaua app-network
    networks:
      - app-network

volumes:
  mongodb_data:

networks:
  app-network:
    driver: bridge # bridge permite containerele sa comunice intre ele in timp ce raman izolate de retea