services:
  app:
    build: .
    ports:
      - "8000:8080"
    volumes:
      - ./src:/app/src # Montează codul sursă local în container
      - ./target:/app/target # Montează directorul de build
      - ~/.m2:/root/.m2 # Cache pentru dependințele Maven
    env_file:
      - .env
    depends_on:
      mongodb:
        condition: service_started
    networks:
      - app-network
    command: mvn spring-boot:run

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

    # serviciul mongodb face parte din reteaua app-network
    networks:
      - app-network

volumes:
  mongodb_data:

networks:
  app-network:
    driver: bridge # bridge permite containerele sa comunice intre ele in timp ce raman izolate de retea