apiVersion: apps/v1
kind: Deployment
metadata:
  name: inchiriaza-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inchiriaza-app
  template:
    metadata:
      labels:
        app: inchiriaza-app
    spec:
      containers:
      - name: inchiriaza-app
        image: gcr.io/inchiriazausor/inchiriaza-app:prod
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_DATA_MONGODB_HOST
          value: "mongodb-service"
    